[package]
name = "antr"
version = "1.0.0"
authors = ["Juan Ibiapina <juanibiapina@gmail.com>"]
description = "A simple to use file system event watcher that runs arbitrary commands"
repository = "https://github.com/juanibiapina/antr"
readme = "README.md"
license = "MIT"

[dependencies]
env_logger = "*"
git2 = "*"
log = "*"
notify = "*"
notify-debouncer-mini = "*"
