[package]
name = "antr"
version = "0.4.0"
authors = ["Juan Ibiapina <juanibiapina@gmail.com>"]
description = "A simple to use file system event watcher that runs arbitrary commands"
repository = "https://github.com/juanibiapina/antr"
readme = "README.md"
license = "MIT"

[dependencies]
notify = "^4.0.13"
git2 = "0.10"
